source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PNXMPPFramework_Example', :exclusive => true do
  pod 'PNXMPPFramework', :path => '../'
end

target 'PNXMPPFramework_Tests', :exclusive => true do
  pod 'PNXMPPFramework', :path => '../'

  pod 'FBSnapshotTestCase'
end
